# Write your MySQL query statement below
SELECT PROJECT_ID, ROUND(SUM(EXPERIENCE_YEARS)/COUNT(EXPERIENCE_YEARS),2) AS AVERAGE_YEARS
FROM PROJECT
JOIN EMPLOYEE ON PROJECT.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
GROUP BY PROJECT_ID;